---
language: php
branches:
  only:
    - master
php:
  - 7.2

before_script:
  - composer self-update
  - composer update --prefer-source
script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
