---
language: php
branches:
  only:
    - master
php:
  - 5.5

before_script:
  - composer self-update
  - composer update
script:
  - phpunit --coverage-clover=coverage.clover --configuration travis-phpunit.xml.dist
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
